ALTER TABLE partners
    ADD COLUMN IF NOT EXISTS partner_type VARCHAR(30) NOT NULL DEFAULT 'ООО',
    ADD COLUMN IF NOT EXISTS address VARCHAR(500) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS director VARCHAR(255) NOT NULL DEFAULT '';
